name:  hashnode blog post 
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  hashnode:
    name: Update this repos README 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          comment_tag_name: "HASHNODE_BLOG"

          feed_list: "https://1-siddheshvlog.hashnode.dev/series/javascript-blogs"  
