name: Latest hashnode blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-hashnode-blog-post:  
    name: Update this repo's README with latest hashnode blog post 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull in hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          comment_tag_name: "HASHNODE_BLOG"
          feed_list: "https://1-siddheshvlog.hashnode.dev/rss.xml"
